[package]
name = "myapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mymacros = { path = "../mymacros" }
parse = "0.1.2"
syn = "2.0.60"
